### ISSUE TITLE
Animation does not start when calling .start()

### ISSUE THREAD

**Issue by huutuesn** [alnitak/yoda#1]
Here is the log

The following RangeError was thrown during paint():
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      YodaExplode.paint (package:yoda/src/yoda_explode.dart:27:47)
#2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:571:13)
#3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:613:7)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#9      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2900:15)
#10     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:654:5)
#11     RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#16     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:155:11)
#17     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:98:5)
#18     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:250:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:231:7)
#20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#29     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2900:15)
#30     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:654:5)
#31     RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#35     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:609:11)
#36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#38     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#39     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2098:15)
#40     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:550:14)
#41     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2085:21)
#42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#44     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7511:15)
#45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#47     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#48     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#50     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2900:15)
#51     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1088:7)
#52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#54     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2900:15)
#55     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:654:5)
#56     RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#59     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7511:15)
#60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#61     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#62     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#64     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#65     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#66     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#67     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#68     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#69     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#70     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:155:11)
#71     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:98:5)
#72     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1116:31)
#73     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:515:19)
#74     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#75     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#76     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#77     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#78     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#79     _invoke (dart:ui/hooks.dart:148:13)
#80     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#81     _drawFrame (dart:ui/hooks.dart:115:31)

**Comment by alnitak** [comment]
Hi,
have you tried if this error happens in the example also? Can you also provide to me a minimal example? Because I can't reproduce it

**Comment by huutuesn** [comment]
@alnitak the sample works fine. I think error happens when the postioned widgets overlaped.
